### ISSUE TITLE
Instructions on how to run the application would be useful

### ISSUE THREAD

**Issue by ghost** [BTBurke/svg-embed-font#1]
This tool looks neat, but you haven't provided information any installation instructions. The command doesn't work as you described. Assuming 'go' is a prerequisite?

**Comment by BTBurke** [comment]
There are pretty comprehensive instructions in the readme.  Did you download the binary for your OS from the releases page?  There's a link to it at the bottom of the readme.

**Comment by ghost** [comment]
@BTBurke sorry I overlooked that you had responded. Forgive me for saying but the Readme doesn't include the basics about Go. I had not used Go before, and so I had to research elsewhere how to actually compile this app. Your Readme assumes prior knowledge of Go basically. I find this issue quite a lot across Github. Composer is another one which is often thrown around but nobody provides an explanation about how to install it on different systems. Fortunately brew supports it now.

**Comment by ghost** [comment]
Anyway, I did manage to compile it in the end and use the tool. It was very useful, thanks :)

**Comment by BTBurke** [comment]
Glad you were able to get it to work.  The nice thing about Go is that it cross-compiles binaries for OS X, Windows, and Linux, so you really shouldn't have to compile anything for most Go projects.  You can just download the pre-compiled binary from the releases page.
